export const themes = {
  dark: {
    backgroundDiv: "bg-red-500",
    titleColor: "text-blue-400",
    heroTitleFontWeight: "font-medium",
    heroTitleFocus: "",
    subtitleColor: "text-blue-400",
    textColor: "fontLighter",
    mainColor: "lighter",
    secondaryColor: "darker",
    themeButtonPrimary: "light",
    themeButton: "light",
  },

  light: {
    backgroundDiv: "bg-white/90",
    titleColor: "text-fontDarker",
    heroTitleFontWeight: "font-medium",
    heroTitleFocus: "font-extrabold text-lighter",
    subtitleColor: "text-fontDarker",
    textColor: "fontDarker",
    mainColor: "lighter",
    secondaryColor: "darker",
    themeButtonPrimary: "light",
    themeButton: "dark",
  },

  default: {
    backgroundDiv: "bg-black/90",
    titleColor: "text-white",
    heroTitleFontWeight: "font-medium",
    heroTitleFocus: "font-extrabold",
    subtitleColor: "text-white",
    textColor: "fontLighter",
    mainColor: "lighter",
    secondaryColor: "darker",
    themeButtonPrimary: "light",
    themeButton: "dark",
  },
};
